### ISSUE TITLE
Audio doesn't play

### ISSUE THREAD

**Issue by kylejlin** [Ameobea/web-synth#7]
I went to [https://notes.ameo.design/](https://notes.ameo.design/) and opened the virtual (piano) keyboard. I tried both clicking the keys on virtual (piano) keyboard and pressing the keys on my physical (computer) keyboard. Both times, the virtual keys lit up, but no sound was emitted.

I went to another website to verify that my computer's audio was working—it was. Then I returned to Web Synth and tried again. Still no luck.

I opened the console and saw the following warning:

```
"The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page."
```

Screenshot:

![Screen Shot 2021-02-23 at 10 04 45 PM](https://user-images.githubusercontent.com/19898960/108955856-b060d100-7623-11eb-8da4-caf0aa346c26.png)

I produced this bug using Google Chrome 88.0.4324.182 running on a MacBook Pro with macOS Big Sur.

**Comment by Ameobea** [comment]
Hi,

Thanks for the report!  I've added some code that should automatically enable the audio context when any event (click, keypress, touchscreen tap) occurs.  However, note that the main tool still needs a lot of work before it's easily usable; I need to write a lot of docs, make a lot of UI improvements, and fix bugs.

Thanks for checking this out though, and again tyvm for this report!
